version: "2"

services:
  mysql:
    container_name: "dzp-mysql"
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: poker
      MYSQL_USER: poker
      MYSQL_PASSWORD: 123456
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql/conf.d:/etc/mysql/conf.d
      - ../database/poker.sql:/docker-entrypoint-initdb.d/99.poker.sql
    networks:
      - app-network

  redis:
    container_name: "dzp-redis"
    image: redis
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass 123456'
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - app-network

  nginx:
    image: lionyuyu/texas-poker-game:nginx-latest
    build:
      context: ../client
      args:
        # DO NOT forgot to update Dockerfile
        NODE_ENV: production
        IDENTIFY_VERSION_KEY: ${IDENTIFY_VERSION_KEY}
    container_name: "dzp-nginx"
    restart: always
    ports:
      - 1111:80
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/htpasswd:/etc/nginx/htpasswd
    networks:
      - app-network

  api:
    image: lionyuyu/texas-poker-game:api-latest
    build:
      context: ../server
      args:
        NODE_ENV: production
        IDENTIFY_VERSION_KEY: ${IDENTIFY_VERSION_KEY}
    container_name: "dzp-api"
    restart: always
    environment:
      NODE_ENV: production
    expose:
      - 7001:7001
    volumes:
      - ./data/server/logs:/root/logs
      - ./data/server/run:/app/run
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
